application: gae-init
version: 1
runtime: python27
api_version: 1
threadsafe: yes

builtins:
- remote_api: on
- deferred: on
- appstats: on
- admin_redirect: on

libraries:
- name: jinja2
  version: latest

handlers:
- url: /(favicon\.ico|robots\.txt)
  static_files: static/\1
  upload: static/(.*)

- url: /gae_mini_profiler/static
  static_dir: libx/gae_mini_profiler/static

- url: /gae_mini_profiler/.*
  script: libx.gae_mini_profiler.main.application

- url: /p/
  static_dir: static/
  expiration: 1000d

- url: /.*
  script: main.app

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$
- ^(.*/)?Icon\r
- ^lib/.*
- ^static/src/.*
- ^static/lib/.*
- ^static/dst/.*
